#!/bin/bash

cmd=$(basename $0)

AUTHDB=auth

SHELL=/bin/sh
GROUP=100
MYHOME=/home
INACTIVE=-1
EXPIRE=
SKEL=/etc/skel
CREATE_MAIL_SPOOL=yes

DB=$(grep database /etc/libnss-mysql.cfg | awk '{print $2}')
DBHost=$(grep host /etc/libnss-mysql.cfg | awk '{print $2}')
NSSUSER=$(grep username /etc/libnss-mysql.cfg  | awk '{print $2}')
NSSUSERPW=$(grep password /etc/libnss-mysql.cfg | awk '{print $2}')

#
# User and Password are supposed to come from ~/my.cnf for root
#

if [ "$EUID" == 0 ]
then
	MyCNF=~root/.my.cnf
else
	#
	# *** Create a my.cnf file for nss-user and reference that
	#
	MyCNF="$(mktemp /tmp/mycnf.$$)"
	cat << EOF >  "$MyCNF"
[client]
user = $NSSUSER
password = $NSSUSERPW
EOF
fi

DefaultsFile="/etc/defaults/useradd"
[ -e "$DefaultsFile" ] && . "$DefaultsFile"

DefaultAddUserConf="/etc/adduser.conf"
[ -e "$DefaultAddUserConf" ] && . "$DefaultAddUserConf"


function warning {
	echo "$@" 1>&2
}

function sys {
	[ -n "${opt_n}${opt_v}" ] && echo "$@" 1>&2

	if [ -z "$opt_n" ]
	then
		"$@"
	fi
}

function mySQL {
	if [ -n "$1" ]
	then
		mysql -Bsh "$DBHost" -e "$@" "$AUTHDB" 
	else
		mysql -Bsh "$DBHost" "$AUTHDB" 
	fi
}

#
# opt_v executes mysql and passes the mysql to stdout
# opt_n no-ops the mysql command, and only copys input to output
#
function verbMySQL {
	if [ -z "$opt_n" ]
	then
	    if [ -n "$opt_v" ]
	    then
		tee >(mysql -Bsh "$DBHost" $AUTHDB 1>&2)
	    else
		mySQL 
	    fi
	else
	    cat
	fi
}

function encryptPassword {
	openssl passwd -1 "$1"
}

function genUserAddSQL {

   	local SQLUName="$1"
	local SQLEPW="$2"
	local SQLUID="$3"
	local SQLGID="$4"
	local SQLGECOS="$5"
	local SQLHDir="$6"
	local SQLShell="$7"
	
	cat << EOF 
	INSERT INTO users (username,password,uid,gid,gecos,homedir,shell)
	    VALUES ('$SQLUName', '$SQLEPW', '$SQLUID', '$SQLGID', '$SQLGECOS', '$SQLHDir', '$SQLShell');
EOF
}

function genGroupAddSQL {

        local SQLGName="$1"
	local SQLGID="$2"

	cat <<EOF
	INSERT INTO groups (name,gid)
	    VALUES ('$SQLGName','$SQLGID');
EOF
}

function genGroupAddUserSQL {

    	local SQLGID="$1"
	local i
	shift

	for i in "$@"
	do
	    cat << EOF
	INSERT INTO grouplist (gid,username)
	    VALUES ($SQLGID,'$i');
EOF
	done
}

function addUser_MySQL {
    	genUserAddSQL "$@" | verbMySQL
}

function addGroup_MySQL {
	genGroupAddSQL "$@" | verbMySQL
}

function addUserToGroup_MySQL {
	genGroupAddUserSQL "$@" | verbMySQL
}

function getNextUid {
	local Uid=$(mysql -Bsh "$DBHost" -e 'SELECT uid FROM users ORDER BY uid DESC LIMIT 1' auth)
	echo $((++Uid))
}

function getNextSysUid {
	local SysUid=$(mysql -Bsh "$DBHost" -e "SELECT uid FROM users WHERE uid >= $FIRST_SYSTEM_UID and uid <= $LAST_SYSTEM_UID ORDER BY gid DESC LIMIT 1" auth)
	if [ -z "$SysUID" ]
	then
		SysUid=$FIRST_SYSTEM_UID
	fi

	echo $SysUid
}

function getGroupIDByName {
	local GName="$1"

	mySQL "SELECT gid FROM groups WHERE name = '$GName' ORDER BY gid DESC"
}

function getNextGid {
	local Gid=$(mySQL 'select gid from groups order by gid desc limit 1' )

	echo $((++Gid))
}

function addUsersToGroup {
	local Sub=AddUsersToGroup
	local G="$1"
	local Gid

	if [ -z "$G" ]
	then
		warning "$cmd($Sub) : Missing Group"
		return 1
	fi

	shift

	if echo "$G" | grep -q -P '^\d+$'
	then
		Gid="$G"
	else
		Gid=$(getGroupIDByName "$G")
		if [ -z "$Gid" ]
		then
			warning "$cmd($Sub) : Invalid Group Name '$G'"
			return 2
		fi
	fi

	for i in "$@"
	do
		if ! addUserToGroup_MySQL "$Gid" $i
		then
			warning "$cmd($Sub) : Could not add '$i' to $Gid"
			return 3
		fi
	done
}

while getopts "b:c:d:e:f:g:G:hk:K:lmMNop:rR:s:u:Uz" arg
do
	case $arg in
	    #
	    # Ignore these flags for now
	    #
	    b|D|e|f|k|K|l|N|o|R|z)
		;;
	    *)
		eval "opt_${arg}=${OPTARG:=1}"
		;;
	esac
done

shift $((OPTIND - 1))

UName=$1

if [ -n "$opt_c" ]
then
	GeCOS="$opt_c"
else
	GeCOS="$UName"
fi

if [ -n "$opt_d" ]
then
	HDir="$opt_d"
else
	HDir="$MYHOME/$UName"
fi

GName="$UName"
if [ -n "$opt_g" ]
then
	Gid=$opt_g
else
	Gid=$(getNextGid)
fi

if [ -n "$opt_m" ]
then
	CREATE_HOME=1
fi

if [ -n "$opt_p" ]
then
	EPW=$(encryptPassword "$opt_p")
else
	EPW='x'
fi

if [ -n "$opt_s" ]
then
	SHELL="$opt_s"
fi

if [ -n "$opt_u" ]
then
	Uid=$opt_u
else
	if [ -n "$opt_r" ]
	then
	    Uid=$(getNextSysUid)
	else
	    Uid=$(getNextUid)
	fi
fi

addUser_MySQL "$UName" "$EPW" "$Uid" "$Gid" "$GeCOS" "$HDir" "$SHELL"
addGroup_MySQL "$GName" "$Gid"

for i in "$Gid" $(echo $opt_G | sed 's/,/ /g')
do
	addUsersToGroup "$i" "$UName"
done

if [ -n "$CREATE_HOME" ]
then
	[ -e "$HDir" ] || sys mkdir "$HDir"
	sys rsync -a "${SKEL}/" "$HDir/"
	sys chown -R "${UName}.${Gid}" "$HDir"
fi
