---
  - name: Install Pam/NSS Packages
    apt: name={{ item }}
    with_items:
      - libnss-mysql-bg
      - libpam-mysql

  - name: Fix libnss-mysql.cfg host
    lineinfile: "dest=/etc/libnss-mysql.cfg state=present regexp='^host' line='host	{{ nss_mysql_host }}'"

  - name: Fix libnss-mysql user password
    lineinfile: "dest=/etc/libnss-mysql.cfg state=present regexp='^password' line='password	{{ nss_mysql_user_password }}'"

  - name: Fix libnss-mysql root password
    lineinfile: "dest=/etc/libnss-mysql-root.cfg state=present regexp='^password' line='password	{{ nss_mysql_root_password }}'"

  - name: Add mysql to passwd in nssswitch.conf
    lineinfile: "dest=/etc/nsswitch.conf state=present regexp='^passwd:' line='passwd:	compat mysql'"

  - name: Add mysql to shadow in nssswitch.conf
    lineinfile: "dest=/etc/nsswitch.conf state=present regexp='^shadow:' line='shadow:	compat mysql'"

  - name: Add mysql to gropu in nssswitch.conf
    lineinfile: "dest=/etc/nsswitch.conf state=present regexp='^group:' line='group:	compat mysql'"
