	setUserLastDayMySQL "$User" "$opt_d"
	setUserExpireDateMySQL "$User" "$opt_E"
	setUserInactiveMySQL "$User" "$opt_I"
	getUserAgingMySQL "$User" "$opt_l"
	setUserMinDaysMySQL "$User" "$opt_m"
	setUserMaxDaysMySQL "$User" "$opt_M"
	setUserWarnDaysMySQL "$User" "$opt_W"
addUser_MySQL "$UName" "$EPW" "$Uid" "$Gid" "$GeCOS" "$HDir" "$SHELL"
addGroup_MySQL "$GName" "$Gid"
rmUserMySQL "$User"
rmUserFromGroupsMySQL "$User" 
rmGroupMySQL "$User"
	setUserGeCOSMySQL "$User" "$opt_c"
	setUserHDirMySQL "$User" "$opt_d"
	setUserGidMySQL "$User" "$opt_g"
	setUserUNameMySQL "$User" "$opt_l"
	setUserEPWMySQL "$User" "$opt_p"
	setUserShellMySQL "$User" "$opt_s"
	setUserUidMySQL "$User" "$opt_u"
